save_latest: yes
waypoints:
  - x:  0.0
    y:  0.0
    z:  1.0
  - x:  5.0
    y:  5.0
    z:  1.0
  - x:  5.0
    y: -5.0
    z:  1.0
  - x: -5.0
    y: -5.0
    z:  1.0
  - x:  5.0
    y: -5.0
    z:  1.0
