save_latest:    no  # Saves newly added waypoints to this config file
                    #   - Only works is 'update_patrol' is also enabled
update_patrol: yes  # Adds newly added waypoints to future patrols
waypoints:
  - x:  0.0
    y:  0.0
    z:  1.0
  - x:  5.0
    y:  5.0
    z:  1.0
  - x:  5.0
    y: -5.0
    z:  1.0
  - x: -5.0
    y: -5.0
    z:  1.0
  - x:  5.0
    y: -5.0
    z:  1.0
